### ISSUE TITLE
Cannot install unknown horizons/fife

### ISSUE THREAD

**Issue by Keridos** [emcek/gentoo.mipl#1]
Fife fails to emerge as it fails to find sdl-ttf/sdl2-ttf although both are install on my system.

scons: Configure: Checking for SDL_ttf (using pkg-config)...
pkg-config --libs --cflags 'sdl_ttf'
Package sdl_ttf was not found in the pkg-config search path.
Perhaps you should add the directory containing `sdl_ttf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sdl_ttf' found
scons: Configure: no

There is the problem, it is SDL_ttf, not sdl_ttf
pkg-config --libs --cflags 'SDL_ttf' works fine for me.

**Comment by emcek** [comment]
thx. I have problem with fife 5 mouths ago, hadn't time to troubleshoot since then. I will try to take a look and fix it.

**Comment by emcek** [comment]
Done. UH with fife should be emerge successfully (only live ebuild). If you use my repo just:

echo "=games-engines/fifechan-9999::mipl_emc *_" >> /etc/portage/package.accept_keywords
echo "=games-engines/fife-9999::mipl_emc *_" >> /etc/portage/package.accept_keywords
echo "=games-strategy/unknown-horizons-9999::mipl_emc **" >> /etc/portage/package.accept_keywords
emerge -pv unknown-horizons

[ebuild   R   *] games-engines/fifechan-9999::mipl_emc  USE="opengl sdl -allegro" 0 kB
[ebuild   R   *] games-engines/fife-9999::mipl_emc  USE="atlas fifechan opengl tinyxml -debug -profile" PYTHON_SINGLE_TARGET="python2_7" PYTHON_TARGETS="python2_7" 0 kB
[ebuild   R   *] games-strategy/unknown-horizons-9999::mipl_emc  PYTHON_TARGETS="python2_7" 0 kB

If you use you local ebuild plese note I test fife only with USE'"atlas fifechan tinyxml -debug -profile"

**Comment by emcek** [comment]
please you last commit:
https://github.com/emcek/gentoo.mipl/commit/e3eaea1cf1b0d99392523885320b83f6c58dc963

**Comment by Keridos** [comment]
Now i cannot start it, it tells me it cannot find/load fife.

**Comment by emcek** [comment]
ebuild is really wrong... I'm work on it.

**Comment by Keridos** [comment]
Any Progress on it yet? Just ask me if you need additional info

**Comment by emcek** [comment]
I was on vacation, I hope i can fix it soon...

**Comment by Keridos** [comment]
Take your time, and thanks for the repository :)

**Comment by emcek** [comment]
You can try **2013.3** first and if it success you can try upgrade to **2014.1** 
I didn't try yet :|
