### ISSUE TITLE
Can't install atom because atom-shell needs llvm 3.4

### ISSUE THREAD

**Issue by jorgicio** [emcek/gentoo.mipl#2]
Hi! I think Atom Shell can compile well with LLVM 3.5 and also Clang (the last one is good) But by now, Atom-shell needs, according to your ebuilds, LLVM3.4, which conflicts with LLVM 3.5 because latest version of Mesa needs LLVM 3.5.

Please, can you fix it?

Thanks.

**Comment by emcek** [comment]
Ok, updated to lvm-3.5 and I decide to update nodejs-10.35 ~amd64 see:
https://github.com/atom/atom/releases/tag/v0.170.0

**Comment by emcek** [comment]
you should useatom-176 with shell-0.20.6 older doesn't work for some reson.
