### ISSUE TITLE
Cannot install app-editors/atom-1.0.11

### ISSUE THREAD

**Issue by dniku** [emcek/gentoo.mipl#8]
Installation fails with

```
emerge: there are no ebuilds to satisfy "<net-libs/nodejs-0.12.6[npm]"
```

The oldest version in the tree is 0.12.6.

**Comment by emcek** [comment]
wrong commit but make pull and try atom-bin version

**Comment by dniku** [comment]
`atom-bin` worked even before the update. Since there have been no updates to the `atom` ebuild, I suppose it is premature to close the issue?

**Comment by emcek** [comment]
I've tried make ebuild for electron (new atom-shell) but I failed :(
